# Generated by Django 4.2.5 on 2023-09-22 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 2, 30, 48, 917766)),
        ),
    ]
