# Generated by Django 4.2.5 on 2023-09-23 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0008_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 11, 59, 36, 520807)),
        ),
    ]
