# Generated by Django 4.2.5 on 2023-09-23 06:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0013_alter_category_created_at'),
        ('manage_user', '0013_alter_customer_registered_at'),
        ('manage_order', '0009_alter_order_placed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 12, 14, 50, 659065)),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=5)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('review_time', models.DateTimeField(default=datetime.datetime(2023, 9, 23, 12, 14, 50, 660065))),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_user.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_product.product')),
            ],
        ),
    ]
