# Generated by Django 5.0.4 on 2024-04-26 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0014_alter_order_placed_at_alter_ordereditem_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 11, 59, 57, 205250)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 11, 59, 57, 205250)),
        ),
    ]
