# Generated by Django 4.2.13 on 2024-05-18 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_order', '0016_alter_order_placed_at_alter_review_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 22, 15, 16, 276618)),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 22, 15, 16, 277622)),
        ),
    ]
