# Generated by Django 3.2.5 on 2021-07-12 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DP',
            new_name='Product',
        ),
    ]
