# Generated by Django 3.2.5 on 2021-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_product_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('pitol', 'Pitol'), ('dinner', 'Dinner Set'), ('plastic', 'Plastic'), ('cooker', 'Cooker')], max_length=100),
        ),
    ]
