# Generated by Django 3.2.5 on 2021-07-14 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_product', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='card',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manage_product.product'),
        ),
    ]
