# Generated by Django 3.2.5 on 2021-07-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0006_auto_20210714_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(choices=[('pitol', 'Pitol'), ('dinner', 'Dinner Set'), ('plastic', 'Plastic')], max_length=100),
        ),
    ]
