# Generated by Django 4.2.5 on 2023-09-23 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0011_alter_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 11, 59, 36, 517811)),
        ),
    ]
