# Generated by Django 4.2.5 on 2023-09-23 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_product', '0012_category_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 23, 12, 14, 50, 657066)),
        ),
    ]
