# Generated by Django 3.2.5 on 2021-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic'),
        ),
    ]
