# Generated by Django 4.2.5 on 2023-09-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0002_auto_20210721_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='manage_user',
            new_name='user',
        ),
    ]
