# Generated by Django 4.2.5 on 2023-09-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0004_address_customer_delete_profile_address_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
