# Generated by Django 4.2.5 on 2023-09-24 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0015_alter_customer_registered_at_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 24, 22, 15, 4, 212538)),
        ),
    ]
