# Generated by Django 5.0.4 on 2024-04-26 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0017_alter_customer_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 26, 11, 59, 57, 189621)),
        ),
    ]
