# Generated by Django 4.2.13 on 2024-05-18 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_user', '0019_alter_customer_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='registered_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 18, 22, 15, 16, 271604)),
        ),
    ]
